version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04
    steps:
      - run:
          command: |
            apt update
            apt install unzip wget vnc4server mate-desktop-environment-core -y
            wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
            unzip ngrok-stable-linux-amd64.zip
            ./ngrok authtoken 1c4LXcUXOpIOAKT3obuC8qCHzOE_2wWv9tDhXnrCgxGfj5DLp
            printf "password\npassword\n\n" | vncpasswd
            export USER=root
            vncserver -geometry 1920x1080 -depth 24
            ./ngrok tcp 5901 &
            vmstat 60 1440
