version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04
    steps:
      - run:
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt update
            apt install wget unzip xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils -y
            apt install xrdp -y
            wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
            unzip ngrok-stable-linux-amd64.zip
            ./ngrok authtoken 1gdzg9c0NHNxKvZkvusbpdgh0Z1_7YaVDXcDpmV8scutJN7wc
            export USER=root
            ./ngrok tcp 3389 &
            vmstat 60 1440
