version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04
    steps:
      - run:
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt update
            apt install unzip wget vnc4server xfce4 xfce4-terminal chromium-browser -y
            wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
            unzip ngrok-stable-linux-amd64.zip
            ./ngrok authtoken 1gdzg9c0NHNxKvZkvusbpdgh0Z1_7YaVDXcDpmV8scutJN7wc
            printf "password\npassword\n\n" | vncpasswd
            export USER=root
            vncserver -geometry 1920x1080 -depth 24
            ./ngrok tcp 5901 &
            chromium-browser --no-sandbox &
            vmstat 60 1440
