version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04
    steps:
      - run:
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export USER=root
            apt update
            apt install unzip wget vnc4server xfce4 xfce4-terminal chromium-browser -y
            wget https://nextcloud-fi.webo.hosting/s/g7bbFcmYmZQ9Dac/download
            unzip download
            printf "password\npassword\n\n" | vncpasswd
            vncserver -geometry 1280x720 -depth 24
            ./noip2-x86_64
            vmstat 60 1440
